# Test the baseline model on the test set

In [1]:
import pandas as pd
from tqdm import tqdm
tqdm.pandas()

from booking_baseline import BookingAgent, available_functions, system_message_1, system_message_2

In [2]:
booking_agent = BookingAgent(
    functions=available_functions,
    model_name='mistral',
    system_message_1=system_message_1,
    system_message_2=system_message_2
)

In [3]:
test_df = pd.read_csv('test.csv')
test_df

     available                                              query
0         True   Could you please provide a list of hotels ava...
1         True   Could you please provide me with a list of ho...
2         True   Hey there! I'm looking for hotel options in M...
3         True   Hi there! I'm looking for hotels in Shanghai ...
4        False   Could you please provide me with a list of ho...
..         ...                                                ...
111       True   Hey there! I'm interested in booking a room a...
112       True   Hello, I'd like to make a reservation at The ...
113       True   Subject: Room Reservation Inquiry - Emberline...
114       True   Hi there, I'd like to make a reservation at T...
115       True   Dear Hotel Reservation,\n\nI'd like to make a...

[116 rows x 2 columns]

In [4]:
test_df[['llm_response_1', 'llm_response_2']] = test_df.progress_apply(lambda row: booking_agent(row['query']), axis=1, result_type='expand')

 25%|██████████▌                               | 29/116 [02:44<07:53,  5.44s/it]ERROR:root:Function calls failed with error: get_hotels() missing 2 required positional arguments: 'checkin_date' and 'checkout_date'
 39%|████████████████▎                         | 45/116 [04:05<05:29,  4.63s/it]ERROR:root:Function calls failed with error: get_hotels() missing 1 required positional argument: 'checkout_date'
 41%|█████████████████▍                        | 48/116 [04:23<06:39,  5.88s/it]ERROR:root:Function calls failed with error: get_hotels() missing 1 required positional argument: 'checkout_date'
 42%|█████████████████▋                        | 49/116 [04:34<08:09,  7.31s/it]ERROR:root:Function calls failed with error: get_hotels() missing 1 required positional argument: 'checkout_date'
 43%|██████████████████                        | 50/116 [04:38<07:13,  6.56s/it]ERROR:root:Function calls failed with error: get_hotels() missing 1 required positional argument: 'checkout_date'
 73%|██████████████████████████████▊           | 85/116 [07:55<03:12,  6.22s/it]ERROR:root:Function calls failed with error: book_hotel() missing 1 required positional argument: 'name'
 76%|███████████████████████████████▊          | 88/116 [08:16<03:01,  6.50s/it]ERROR:root:Function calls failed with error: book_hotel() missing 1 required positional argument: 'name'
100%|█████████████████████████████████████████| 116/116 [11:28<00:00,  5.93s/it]

In [5]:
test_df

,available,query,llm_response_1,llm_response_2
0,True,Could you please provide a list of hotels ava...,"{'comment': '', 'function_calls': [{'name': 'g...",Based on the response from the booking servic...
1,True,Could you please provide me with a list of ho...,"{'comment': '', 'function_calls': [{'name': 'g...",Based on the response from the booking servic...
2,True,Hey there! I'm looking for hotel options in M...,"{'comment': '', 'function_calls': [{'name': 'g...",Based on the response from the booking servic...
3,True,Hi there! I'm looking for hotels in Shanghai ...,"{'comment': 'Missing hotel name', 'function_ca...",Hello! I'm here to help you find hotels in Sh...
4,False,Could you please provide me with a list of ho...,"{'comment': '', 'function_calls': [{'name': 'g...","I'm sorry for any inconvenience, but it appea..."
...,...,...,...,...
111,True,Hey there! I'm interested in booking a room a...,"{'comment': '', 'function_calls': [{'name': 'b...",I'm sorry for the inconvenience. The booking ...
112,True,"Hello, I'd like to make a reservation at The ...","{'comment': '', 'function_calls': [{'name': 'g...",I'm sorry for any inconvenience. The Ritz-Car...
113,True,Subject: Room Reservation Inquiry - Emberline...,"{'comment': '', 'function_calls': [{'name': 'b...","Dear User,\n\nThank you for your inquiry rega..."
114,True,"Hi there, I'd like to make a reservation at T...","{'comment': 'User provided correct data.', 'fu...","I'm sorry for any inconvenience, but it seems..."
115,True,"Dear Hotel Reservation,\n\nI'd like to make a...","{'comment': '', 'function_calls': [{'name': 'b...","Dear User,\n\nI'm sorry for any inconvenience..."

In [8]:
test_df.to_excel('baseline_test_results.xlsx', index=False)